local VLib = loadstring(game:HttpGet("https://pastebin.com/raw/Mb49kKTP"))()

MAINTTL = "Vxly"

local win = VLib:Window("Welcome!", Color3.fromRGB(196, 40, 28))

local ss1 = win:Tab("Usage Tutorial")
local ss = win:Tab("New")
local cred = win:Tab("Cred's")
local old = win:Tab("Old")

-- Helper function to create a button for loading scripts from URLs
local function createScriptButton(tab, name, url)
    tab:Button(name, function()
        loadstring(game:HttpGet(url))()
    end)
end

-- HOW TO USE Tab
ss1:Button("Remove GUI", function()
    game.CoreGui["Library"]:Destroy()
end)

ss1:Label("Press the Rainbow Line To Move the GUI")
ss1:Label("All scripts Have Been Verified Of Safety")
ss1:Label("Please Show Credits By Pressing On 'Cred's' Tab")
ss1:Label("Some Scripts May Not Work In Old, We are Still Fixing That.")
ss1:Label("Press Right Control/CTRL To Toggle the GUI")

-- MAIN Tab (Universal Scripts)
local UniversalTab = ss
ss1:Label("Changelog")
ss1:Label("Added Scripts & Adding More Scripts - Version V1")
ss1:Label("Added Support For: Fisch, TOH, Brookhaven, Ability Wars")
createScriptButton(UniversalTab, "Fisch (Recommended For Pro's)", "https://raw.githubusercontent.com/AhmadV99/Speed-Hub-X/main/Speed%20Hub%20X.lua")
createScriptButton(UniversalTab, "Fisch (Recommended For New Player's)", "https://raw.githubusercontent.com/Efe0626/RaitoHub/refs/heads/main/Script")
createScriptButton(UniversalTab, "Ability Wars", "https://raw.githubusercontent.com/railme37509124/komaruhubabilitywars/main/script.lua")
createScriptButton(UniversalTab, "Tower Of Heck", "https://raw.githubusercontent.com/centerepic/sasware_TowerOfHell/main/TowerOfHell_sw.lua")
createScriptButton(UniversalTab, "Bypasser", "https://raw.githubusercontent.com/shakk-code/SigmaBypasser/refs/heads/main/source")
createScriptButton(UniversalTab, "Bedwars", "https://raw.githubusercontent.com/cocotv666/Aurora/main/Aurora_Loader")
createScriptButton(UniversalTab, "Bedwars", "https://raw.githubusercontent.com/goinglikeatrainlol/Raven-B4-Essentials/main/Bedwars")
createScriptButton(UniversalTab, "White Room", "https://orbituniverse.com/spacehub")
createScriptButton(UniversalTab, "MM2", "https://raw.githubusercontent.com/vertex-peak/vertex/refs/heads/main/loadstring")
createScriptButton(UniversalTab, "MM2", "https://raw.githubusercontent.com/Au0yX/Community/main/XhubMM2")
createScriptButton(UniversalTab, "Break in 2", "https://luau.tech/build")

-- OLD Tab (All previous scripts)
old:Label("---- kill gui ----")
old:Button("Destroy Gui", function()
    game.CoreGui["Library"]:Destroy()
end)

old:Label("---- MAIN Tab ----")
old:Button("Dex Explorer", function()
    loadstring(game:HttpGet('https://cdn.wearedevs.net/scripts/Dex%20Explorer.txt'))()
end)
old:Button("Fake-sUNC", function()
    loadstring(game:HttpGet("https://github.com/skintalker/Fake-sUNC/raw/refs/heads/main/Source/Fake-sUNC-Main.lua"))()
end)
old:Button("Sigma Bypasser", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/shakk-code/SigmaBypasser/refs/heads/main/source'))()
end)
old:Button("Backdoor Scanner", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Its-LALOL/LALOL-Hub/main/Backdoor-Scanner/script'))()
end)
old:Button("Infinite Yield", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source"))()
end)

old:Label("---- DOORS Tab ----")
old:Button("BlackKing and BobHub", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/KINGHUB01/BlackKing-obf/main/Doors%20Blackking%20And%20BobHub"))()
end)
old:Button("MSPaint Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/notpoiu/mspaint/main/main.lua"))()
end)
old:Button("Leaf Hub", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/zReal-King/Leaf-Hub/main/Leaf-Hub'))()
end)

old:Label("---- BEDWARS & ARSENAL Tab ----")
old:Button("Vape V4 Rewrite", function()
    loadstring(game:HttpGet("loadstring(game:HttpGet("https://raw.githubusercontent.com/7GrandDadPGN/VapeV4ForRoblox/main/NewMainScript.lua", true))()
end)
old:Button("TbaoHub Arsenal", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/tbao143/thaibao/main/TbaoHubArsenal'))()
end)

old:Label("---- TOWER OF HELL Tab ----")
old:Button("SprinHub", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/dqvh/dqvh/main/SprinHub'))()
end)

old:Label("---- BREAK IN 1/2 & FIELD TRIP Z Tab ----")
old:Button("Break In 1", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Darkmoonxhubscript/BreakIn1/main/BreakIn1'))()
end)
old:Button("Break In 2", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/danielontopp/scripts/main/77_OCM25E2M.lua.txt'))()
end)
old:Button("Field Trip Z", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/sjdhfiuyhknamsldwadkij/dsfe/refs/heads/main/1'))()
end)

old:Label("---- BLOX FRUITS & BLADE BALL Tab ----")
old:Button("Corolla Hub (Blade Ball)", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/7190000/Corolla-Hub/main/ch.lua'))()
end)
old:Button("Pearcathub (Blox Fruits)", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/NguyenLam2504/pearcathub.lua/main/vaicapia.lua'))()
end)

old:Label("---- DTI & MM2 Tab ----")
old:Button("Xhub MM2", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/Au0yX/Community/main/XhubMM2'))()
end)
old:Button("DTI GUI V2", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/hellohellohell012321/DTI-GUI-V2/main/dti_gui_v2.lua'))()
end)

old:Label("---- RIVALS & SANDERX Tab ----")
old:Button("RIVALS Script", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/ByNami/RIVALS/main/RIVALS.lua"))()
end)
old:Button("SanderX Script", function()
    loadstring(game:HttpGet('https://raw.githubusercontent.com/kigredns/SanderXV4.2.2/refs/heads/main/NormalSS.lua'))()
end)

old:LABEL("---- Universal ----")
old:Button("ScriptHub V3", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/scripthubekitten/SCRIPTHUBV3/main/SCRIPTHUBV3", true))()
end)
old:Button("Speed Hub X", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/AhmadV99/Speed-Hub-X/main/Speed%20Hub%20X.lua", true))()
end)
-- CREDITS Tab
cred:Button("Copy YT Link", function()
    setclipboard("https://www.youtube.com/@mysteryzytube")
end)
